### ISSUE TITLE
Alarm Control Panel missing

### ISSUE THREAD

**Issue by jschlyter** [Lundix-IT/spcbridge#4]
Although [spcbridge-card](https://github.com/Lundix-IT/spcbridge-card), I'd guess most users would expect an `alarm_control_panel` entity to be created as well.

**Comment by jschlyter** [comment]
Strangely, the panel was not created directly but some time after the component was loaded.

**Comment by Goran58** [comment]
Since HA's standard alarm control panel is very limited and does not align well with SPC's handling of alarm areas and zones, adding support for it is not under consideration.

**Comment by briis** [comment]
The built-in SPC Integration has an Alarm Panel entity, so it can be done, and it would be really a nice addition to this Integration. So hopefully you will reconsider

**Comment by briis** [comment]
I decided to make the Alarm Control Panel myself. And even though I agree that there are limitations in regards to Zones and Areas, it works for my setup of the SPCBridge and Home Assistant. 
As I also wanted to ensure support for the latest version of Home Assistant, that uses Python 3.14, I made a clone of the project, instead of a Fork. 
The code [can be found here](https://github.com/briis/spcbridge).
